server:
  port: 8008

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/queue_up

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true